web:
  env_file: ./common.env
  build: .
  container_name: dockerphp
  ports:
   - "8080:8080"
  volumes:
    - $HOME/workspace:/var/www/html/workspace
    - ./nginx/vhost.dev:/etc/nginx/sites-enabled/default
    - ./log/nginx:/var/log/nginx
    - ./log/php:/var/log/php
    - ./log/supervisor:/var/log/supervisor
  links:
    - mariadb:dockerphp-mariadb
    - memcached:dockerphp-memcached
    - redis:dockerphp-redis
  environment:
    VIRTUAL_HOST: dockerphp
    VIRTUAL_PORT: 8080

mariadb:
  image: mariadb:10.1.20
  restart: always
  container_name: dockerphp-mariadb
  environment:
    TERM: dumb
    MARIADB_USER: admin
    MARIADB_PASS: admin
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306"
  expose:
    - "3306"

memcached:
  image: memcached:1.4.34
  restart: always
  container_name: dockerphp-memcached
  ports:
    - "11211:11211"
  expose:
    - "11211"

redis:
  image: redis:3.0.7
  restart: always
  container_name: dockerphp-redis
  ports:
    - "6380:6380"
  expose:
    - "6380"
