web:
  build: .
  container_name: dockerphp
  ports:
   - "8080:8080"
  volumes:
    - $HOME/workspace:/var/www/html/workspace
    - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    #
    # Supervisor
    #
    - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    - ./log/supervisor:/var/log/supervisor
    #
    # Nginx
    #
    - ./nginx/vhost.$ENV:/etc/nginx/sites-enabled/default
    - ./log/nginx:/var/log/nginx
    #
    # PHP
    #
    - ./php/php.ini.$ENV:/usr/local/etc/php/php.ini
    - ./log/php:/var/log/php
  #
  # It will create references in "/etc/hosts" file
  #  
  links:
    - mariadb:dockerphp-mariadb
    - memcached:dockerphp-memcached
    - redis:dockerphp-redis
  environment:
    VIRTUAL_HOST: dockerphp
    VIRTUAL_PORT: 8080

mariadb:
  build: ./mariadb

mariadb:
  build: ./mariadb
  restart: always
  container_name: dockerphp-mariadb
  environment:
    TERM: dumb
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306"
  expose:
    - "3306"

memcached:
  build: ./memcached
  restart: always
  container_name: dockerphp-memcached
  ports:
    - "11211:11211"
  expose:
    - "11211"

redis:
  build: ./redis
  restart: always
  container_name: dockerphp-redis
  ports:
    - "6380:6380"
  expose:
    - "6380"
