version: "3.3"
services:
  php:
    build: ./php
    container_name: dockerphp_php
    volumes:
      #
      # Workspace and SSH
      #
      - $HOME/workspace:/var/www/workspace
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      #
      # Supervisor
      #
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./log/supervisor:/var/log/supervisor
      #
      # PHP
      #
      - ./log/php:/var/log/php
    #
    # It will create references in "/etc/hosts" file
    #  
    links:
      - mysql:dockerphp_mysql
      - memcached:dockerphp_memcached
      - redis:dockerphp_redis
      - elasticsearch1:dockerphp_elasticsearch_1
      - rabbitmq:dockerphp_rabbitmq
    depends_on:
        - mysql
  nginx:
    build: ./nginx
    container_name: dockerphp_nginx
    volumes:
      #
      # Workspace and logs
      #
      - $HOME/workspace:/var/www/workspace
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mysql
  #
  # MySQL configuration
  #
  mysql:
    build: ./mysql
    restart: always
    container_name: dockerphp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
        test: exit 0
    volumes:
        - "./data/mysql:/var/lib/mysql"
  #
  # Memcached configuration
  #
  memcached:
    build: ./memcached
    restart: always
    container_name: dockerphp_memcached
  #
  # Redis configuration
  #
  redis:
    build: ./redis
    restart: always
    container_name: dockerphp_redis
  #
  # Elasticsearch configuration (Cluster with 2 nodes)
  #
  # Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  #
  elasticsearch1:
    build: ./elasticsearch
    container_name: dockerphp_elasticsearch_1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:$HOME/data/elasticsearch
    ports:
      - 9200:9200
  elasticsearch2:
    build: ./elasticsearch
    container_name: dockerphp_elasticsearch_2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:$HOME/data/elasticsearch
  #
  # RabbitMQ configuration
  #
  rabbitmq:
    build: ./rabbitmq
    restart: always
    container_name: dockerphp_rabbitmq
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local