web:
  env_file: ./env.conf
  build: .
  container_name: dockerphp
  ports:
   - "8080:8080"
  volumes:
    - $HOME/workspace:/var/www/html/workspace
    - ./nginx/vhost.dev:/etc/nginx/sites-enabled/default
  links:
    - mariadb:mariadb
    - memcached:memcached
    - redis:redis
  environment:
    VIRTUAL_HOST: dockerphp
    VIRTUAL_PORT: 8080

mariadb:
  image: mariadb:10.1.11
  restart: always
  container_name: mariadb
  environment:
    TERM: dumb
    MARIADB_USER: admin
    MARIADB_PASS: admin
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306"
  expose:
    - "3306"

memcached:
  image: memcached:1.4
  restart: always
  container_name: memcached
  ports:
    - "11211:11211"
  expose:
    - "11211"  

redis:
  image: redis:3.0.7
  restart: always
  container_name: redis
  ports:
    - "6380:6380"
  expose:
    - "6380"
